name: Deploy Tudu Principal

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Configuração SSH segura
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TUDU_SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host 89.116.73.70\n  StrictHostKeyChecking yes\n  UserKnownHostsFile ~/.ssh/known_hosts" > ~/.ssh/config
          ssh-keyscan -t ed25519 89.116.73.70 >> ~/.ssh/known_hosts

      # Build otimizado
      - name: Build do Projeto
        uses: actions/setup-node@v4
        with:
          node-version: "20"
        run: |
          npm ci --no-audit
          npm run build -- --configuration=production
          echo "Verificando arquivos buildados:"
          ls -la dist/

      # Deploy com limpeza prévia
      - name: Enviar para o Servidor
        run: |
          ssh -i ~/.ssh/deploy_key deployer@89.116.73.70 "
            # Limpa o diretório mantendo .env e uploads
            rm -rf
          "
          scp -i ~/.ssh/deploy_key -rp dist/* deployer@89.116.73.70:/var/www/tudu/

      # Pós-deploy robusto
      - name: Atualizar Serviços
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 89.116.73.70
          username: deployer
          key: ${{ secrets.TUDU_SERVER_SSH_KEY }}
          script: |
            echo "=== Verificando arquivos no servidor ==="
            ls -la /var/www/tudu/

            echo "=== Reiniciando serviços ==="
            sudo systemctl restart nginx
            pm2 restart tudu-api --update-env

            echo "=== Limpando cache do Nginx ==="
            sudo rm -rf /var/cache/nginx/*
            sudo nginx -t
